# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en
  rtl: ltr
  languagedirection: ltr
  title: Eran Kutner Photography
  weight: 1
  params:
    _merge: deep
    footer:
      copyright:
        notice: '© {year} Eran Kutner'

he:
  languageCode: "he"
  languagedirection: "rtl"
  contentDir: content/he
  title: "צילום ערן קוטנר"
  weight: 2
  params:
    footer:
      copyright:
        notice: '© {year} כל הזכויות שמורות'


# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
