# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Portfolio Images
    url: /gallery/portfolio/
    weight: 20
  - name: Select Photos
    url: /gallery/select/
    weight: 30
  - name: Travel Galleries
    url: /gallery/travel/
    weight: 40
  - name: Private
    url: /prvt/
    weight: 50
    # workaround for bootstrap bug that tries to download the page on mouse over
    # post: >
    #   <script>
    #     var element = document.querySelector('a[href*="prvt"]');
    #     const newItem = document.createElement('a');
    #     newItem.href = "/en/gallery/private/";
    #     newItem.classList.add("nav-link");
    #     newItem.innerHTML = "<span>Private</span>"
    #     element.replaceWith(newItem);
    #     //element.addEventListener("mousedown", function(event){
    #     //  event.stopPropagation();
    #     //  event.preventDefault();
    #     //  event.stopImmediatePropagation()
    #     //  window.location.href = element.href.replace("prvt", "gallery/private/");
    #     // }, true);
    #   </script>

main_right:
  - name: ""
    pre: '<span style="font-size: 1.2em;"><i class="fa-brands fa-instagram" ></i>'
    post: "</span>"
    url: "https://instagram.com/erankutner"
    weight: 10
  - name: " "
    pre: '<span style="font-size: 1.2em;"><i class="fa-brands fa-twitter " ></i>'
    post: "</span>"
    url: "https://twitter.com/ekutner"
    weight: 20

  - name: "   "
    pre: '<span style="font-size: 1.2em;"><i class="fa-brands fa-facebook" ></i>'
    post: "</span>"
    url: "https://facebook.com/ekutner"
    weight: 30