# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_night: minimal
  font: minimal
  font_size: M

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: "Eran Kutner Photography"
    twitter: 'ekutner'
  analytics:
    google_analytics: 'UA-43087203-1'
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: false
    show_language: false
    show_day_night: false
    show_search: true
    highlight_active_link: false

# Site footer

footer:
  copyright:
    notice: '© {year} Eran Kutner. This work is licensed under {license}'
    license:
      enable: false
      allow_derivatives: true
      share_alike: false
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - r
      - latex
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/<username>/<repository>'
    content_dir: content
    branch: master
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
  search:
    provider: algolia
    wowchemy:
      min_length: 2
      threshold: 0.4
    algolia:
      app_id: 'AW1SEXXQZE'
      public_api_key: '683b88d47c2301a91295c8d3b52def49'
      private_api_key: 'abe9833429495397b01ba56c0989c2d9'
      public_index: 'public'
      private_index: 'private'


      show_logo: true
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Security

security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: true


gallery:
  imageResizeOptions: "1920x1080 webp"
  thumbnailResizeOptions: "400x400 webp"
  rowHeight: 300
