default_config:

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Text to speech
tts:
  - platform: google_translate


# Dev config starts here
logger:
  default: info
  logs:
    home_connect_async: debug
    home_connect_alt: debug
    custom_components.home_connect_alt: error
    homeassistant.helpers.config_entry_oauth2_flow: debug

home_connect_alt:
  client_id: !secret home_connect_client_id
  client_secret: !secret home_connect_client_secret
  # cache: false
  language: en-GB
  sensor_value_translation: local
  name_template: $appliance $name ($brand)
  log_mode: 7
  #api_host: https://simulator.home-connect.com
  # entity_settings:
  #   LaundryCare.Washer.Setting.IDos2BaseLevel:
  #     unit: xx
  #     icon: mdi:waves-arrow-up
