default_config:

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Text to speech
tts:
  - platform: google_translate


# Dev config starts here
logger:
  default: warn
  logs:
    home_connect_async: debug
    home_connect_alt: debug
    custom_components.home_connect_alt: debug

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
#debugpy:

home_connect_alt:
  client_id: !secret home_connect_client_id
  client_secret: !secret home_connect_client_secret
  # cache: false
  # simulate: false
  # language: es
  # sensor_value_translation: server
  # name_template: $appliance $name ($brand)
  log_mode: 3

