default_config:

logger:
  default: info
  logs:
    custom_components.home_connect_alt: debug

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
# debugpy:

home_connect_alt:
  client_id: !secret home_connect_client_id
  client_secret: !secret home_connect_client_secret
  simulate: true



